version: "3.7"
services:
  ruby:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    container_name: ruby
    command: /bin/sh -c "rm -rf tmp/pids/server.pid & bin/rails s -b 0.0.0.0"
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      DB_HOST: "mysql"
      DB_USER: "root"
      DB_PASSWORD: ""
    tty: true
    stdin_open: true
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql-data:
