default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('APP_DATABASE_USER') { 'root' } %>
  password: <%= ENV.fetch('APP_DATABASE_PASSWORD') { '' } %>
  host: <%= ENV.fetch("APP_DATABASE_HOST") { 'mysql' } %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test


staging:
  <<: *default
  database: app_staging

production:
  <<: *default
  database: app_production
